#!/bin/bash -l
#SBATCH -q regular
#SBATCH -N 1
#SBATCH -t 03:00:00
#SBATCH -J ips_solps
#SBATCH -e ips.err
#SBATCH -o ips.out
#SBATCH -C cpu

module load python
source activate /global/common/software/atom/perlmutter/cesol/conda/latest

ips.py --simulation=solps_iter.config --platform=$MACHINE_CONFIG --log=ips.log  
