#!/bin/bash -l
#SBATCH -q debug
#SBATCH -N 1 
#SBATCH -t 00:30:00
#SBATCH -J ips_fastran
#SBATCH -e ips.err
#SBATCH -o ips.out
#SBATCH -C cpu

export PYTHONPATH=
module load python
conda activate /global/common/software/atom/perlmutter/cesol/conda/dev

export FASTRAN_BIN_NAME=xfastran_ver1.1_prerelease

ips.py --simulation=fastran_scenario.config --platform=$MACHINE_CONFIG --log=ips.log 

conda deactivate
